### ISSUE TITLE
Add open-graph plugin

### ISSUE THREAD

**Issue by LucaLanziani** [Roma-JS/romajs-on-metalsmith#31]
https://www.npmjs.com/package/metalsmith-open-graph

**Comment by Takeno** [comment]
That plugin is not stable enough and it breaks quote symbol in sources. (Don't know why).

**Comment by LucaLanziani** [comment]
@Takeno do you have an example? We can always open a PR to fix it or try a different plugin

**Comment by Takeno** [comment]
Yeah, I'm working on it
